# DO NOT EDIT! Auto-generated via carmel install.
package Carmel::MySetup;

our %environment = (
  'inc' => [
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/App-Prove-Watch-0.3/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Filesys-Notify-Simple-0.14/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Class-Inspector-1.36/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Class-Method-Modifiers-2.15/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Const-Fast-0.014/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-Tiny-0.051/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/ExtUtils-Config-0.010/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/ExtUtils-Helpers-0.028/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/ExtUtils-InstallPaths-0.014/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Sub-Exporter-Progressive-0.001013/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/ExtUtils-CChecker-0.12/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/File-ShareDir-1.118/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/File-ShareDir-Install-0.14/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Game-Deckar-0.02/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Object-Pad-0.814/blib/arch',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Object-Pad-0.814/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/XS-Parse-Keyword-0.46/blib/arch',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/XS-Parse-Keyword-0.46/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/XS-Parse-Sublike-0.28/blib/arch',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/XS-Parse-Sublike-0.28/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Modern-Perl-1.20241001/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Role-Tiny-2.002004/blib/lib',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Sub-Quote-2.006008/blib/lib'
  ],
  'path' => [
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/App-Prove-Watch-0.3/blib/script',
    '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/script'
  ],
  'execs' => {
    'App::Prove::Watch' => {
      'provewatcher' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/App-Prove-Watch-0.3/blib/script/provewatcher'
    },
    'Module::Build' => {
      'config_data' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/script/config_data'
    }
  },
  'base' => '/home/lancew/dev/mille_bornes',
  'modules' => {
    'App/Prove/Watch.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/App-Prove-Watch-0.3/blib/lib/App/Prove/Watch.pm',
    'Class/Inspector.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Class-Inspector-1.36/blib/lib/Class/Inspector.pm',
    'Class/Inspector/Functions.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Class-Inspector-1.36/blib/lib/Class/Inspector/Functions.pm',
    'Class/Method/Modifiers.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Class-Method-Modifiers-2.15/blib/lib/Class/Method/Modifiers.pm',
    'Const/Fast.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Const-Fast-0.014/blib/lib/Const/Fast.pm',
    'ExtUtils/CChecker.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/ExtUtils-CChecker-0.12/blib/lib/ExtUtils/CChecker.pm',
    'ExtUtils/Config.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/ExtUtils-Config-0.010/blib/lib/ExtUtils/Config.pm',
    'ExtUtils/Config/MakeMaker.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/ExtUtils-Config-0.010/blib/lib/ExtUtils/Config/MakeMaker.pm',
    'ExtUtils/Helpers.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/ExtUtils-Helpers-0.028/blib/lib/ExtUtils/Helpers.pm',
    'ExtUtils/Helpers/Unix.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/ExtUtils-Helpers-0.028/blib/lib/ExtUtils/Helpers/Unix.pm',
    'ExtUtils/Helpers/VMS.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/ExtUtils-Helpers-0.028/blib/lib/ExtUtils/Helpers/VMS.pm',
    'ExtUtils/Helpers/Windows.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/ExtUtils-Helpers-0.028/blib/lib/ExtUtils/Helpers/Windows.pm',
    'ExtUtils/InstallPaths.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/ExtUtils-InstallPaths-0.014/blib/lib/ExtUtils/InstallPaths.pm',
    'File/ShareDir.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/File-ShareDir-1.118/blib/lib/File/ShareDir.pm',
    'File/ShareDir/Install.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/File-ShareDir-Install-0.14/blib/lib/File/ShareDir/Install.pm',
    'Filesys/Notify/Simple.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Filesys-Notify-Simple-0.14/blib/lib/Filesys/Notify/Simple.pm',
    'Game/Deckar.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Game-Deckar-0.02/blib/lib/Game/Deckar.pm',
    'Method/Generate/Accessor.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib/Method/Generate/Accessor.pm',
    'Method/Generate/BuildAll.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib/Method/Generate/BuildAll.pm',
    'Method/Generate/Constructor.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib/Method/Generate/Constructor.pm',
    'Method/Generate/DemolishAll.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib/Method/Generate/DemolishAll.pm',
    'Modern/Perl.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Modern-Perl-1.20241001/blib/lib/Modern/Perl.pm',
    'Module/Build.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build.pm',
    'Module/Build/Base.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Base.pm',
    'Module/Build/Compat.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Compat.pm',
    'Module/Build/Config.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Config.pm',
    'Module/Build/ConfigData.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/ConfigData.pm',
    'Module/Build/Cookbook.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Cookbook.pm',
    'Module/Build/Dumper.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Dumper.pm',
    'Module/Build/Notes.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Notes.pm',
    'Module/Build/PPMMaker.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/PPMMaker.pm',
    'Module/Build/Platform/Default.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Platform/Default.pm',
    'Module/Build/Platform/MacOS.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Platform/MacOS.pm',
    'Module/Build/Platform/Unix.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Platform/Unix.pm',
    'Module/Build/Platform/VMS.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Platform/VMS.pm',
    'Module/Build/Platform/VOS.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Platform/VOS.pm',
    'Module/Build/Platform/Windows.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Platform/Windows.pm',
    'Module/Build/Platform/aix.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Platform/aix.pm',
    'Module/Build/Platform/cygwin.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Platform/cygwin.pm',
    'Module/Build/Platform/darwin.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Platform/darwin.pm',
    'Module/Build/Platform/os2.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/Platform/os2.pm',
    'Module/Build/PodParser.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-0.4234/blib/lib/Module/Build/PodParser.pm',
    'Module/Build/Tiny.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Module-Build-Tiny-0.051/blib/lib/Module/Build/Tiny.pm',
    'Moo.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib/Moo.pm',
    'Moo/HandleMoose.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib/Moo/HandleMoose.pm',
    'Moo/HandleMoose/FakeMetaClass.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib/Moo/HandleMoose/FakeMetaClass.pm',
    'Moo/HandleMoose/_TypeMap.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib/Moo/HandleMoose/_TypeMap.pm',
    'Moo/Object.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib/Moo/Object.pm',
    'Moo/Role.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib/Moo/Role.pm',
    'Moo/_Utils.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib/Moo/_Utils.pm',
    'Moo/sification.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib/Moo/sification.pm',
    'Object/Pad.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Object-Pad-0.814/blib/lib/Object/Pad.pm',
    'Object/Pad/ExtensionBuilder.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Object-Pad-0.814/blib/lib/Object/Pad/ExtensionBuilder.pm',
    'Object/Pad/MOP/Class.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Object-Pad-0.814/blib/lib/Object/Pad/MOP/Class.pm',
    'Object/Pad/MOP/Field.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Object-Pad-0.814/blib/lib/Object/Pad/MOP/Field.pm',
    'Object/Pad/MOP/FieldAttr.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Object-Pad-0.814/blib/lib/Object/Pad/MOP/FieldAttr.pm',
    'Object/Pad/MOP/Method.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Object-Pad-0.814/blib/lib/Object/Pad/MOP/Method.pm',
    'Object/Pad/MetaFunctions.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Object-Pad-0.814/blib/lib/Object/Pad/MetaFunctions.pm',
    'Role/Tiny.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Role-Tiny-2.002004/blib/lib/Role/Tiny.pm',
    'Role/Tiny/With.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Role-Tiny-2.002004/blib/lib/Role/Tiny/With.pm',
    'Sub/Defer.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Sub-Quote-2.006008/blib/lib/Sub/Defer.pm',
    'Sub/Exporter/Progressive.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Sub-Exporter-Progressive-0.001013/blib/lib/Sub/Exporter/Progressive.pm',
    'Sub/Quote.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Sub-Quote-2.006008/blib/lib/Sub/Quote.pm',
    'Sublike/Extended.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/XS-Parse-Sublike-0.28/blib/lib/Sublike/Extended.pm',
    'XS/Parse/Infix.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/XS-Parse-Keyword-0.46/blib/lib/XS/Parse/Infix.pm',
    'XS/Parse/Infix/Builder.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/XS-Parse-Keyword-0.46/blib/lib/XS/Parse/Infix/Builder.pm',
    'XS/Parse/Infix/Builder_data.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/XS-Parse-Keyword-0.46/blib/lib/XS/Parse/Infix/Builder_data.pm',
    'XS/Parse/Keyword.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/XS-Parse-Keyword-0.46/blib/lib/XS/Parse/Keyword.pm',
    'XS/Parse/Keyword/Builder.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/XS-Parse-Keyword-0.46/blib/lib/XS/Parse/Keyword/Builder.pm',
    'XS/Parse/Keyword/Builder_data.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/XS-Parse-Keyword-0.46/blib/lib/XS/Parse/Keyword/Builder_data.pm',
    'XS/Parse/Sublike.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/XS-Parse-Sublike-0.28/blib/lib/XS/Parse/Sublike.pm',
    'XS/Parse/Sublike/Builder.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/XS-Parse-Sublike-0.28/blib/lib/XS/Parse/Sublike/Builder.pm',
    'odern/Perl.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Modern-Perl-1.20241001/blib/lib/odern/Perl.pm',
    'oo.pm' => '/home/lancew/.carmel/5.40.0-x86_64-linux-thread-multi/builds/Moo-2.005005/blib/lib/oo.pm'
  },
  'prereqs' => {
    'runtime' => {
      'requires' => {
        'App::Prove::Watch' => '0',
        'Const::Fast' => '0',
        'Game::Deckar' => '0',
        'List::Util' => '0',
        'Modern::Perl' => '0',
        'Moo' => '0',
        'Test2::V0' => '0'
      }
    }
  },
);

1;
